# Copyright 2020 Signal Messenger, LLC
# SPDX-License-Identifier: AGPL-3.0-only

name: lel-CI
on:
  release:
    types: [published]

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - run: lsb_release -a
    - run: uname -a
    - uses: actions/checkout@v4
    - name: Setup node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
    - run: npm install -g npm@10.2.5

    - name: Restore cached .eslintcache and tsconfig.tsbuildinfo
      uses: actions/cache/restore@v4
      id: cache-lint
      with:
        path: |
          .eslintcache
          tsconfig.tsbuildinfo
        key: lint-${{ runner.os }}-${{ hashFiles('package.json', 'package-lock.json', 'patches/**', '.eslintrc.js', '.eslint/**', 'tsconfig.json') }}

    - name: Cache Desktop node_modules
      id: cache-desktop-modules
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-${{ hashFiles('package.json', 'package-lock.json', 'patches/**') }}

    - name: Install Desktop node_modules
      if: steps.cache-desktop-modules.outputs.cache-hit != 'true'
      run: npm ci
      env:
        NPM_CONFIG_LOGLEVEL: verbose

    - run: npm run generate
    - run: npm run lint
    - run: npm run lint-deps
    # - run: npm run lint-license-comments

    - name: Check acknowledgments file is up to date
      run: npm run build:acknowledgments
      env:
        REQUIRE_SIGNAL_LIB_FILES: 1

    - run: git diff --exit-code

    - name: Update cached .eslintcache and tsconfig.tsbuildinfo
      uses: actions/cache/save@v4
      with:
        path: |
          .eslintcache
          tsconfig.tsbuildinfo
        key: ${{ steps.cache-lint.outputs.cache-primary-key }}

  linux:
    needs: lint
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - run: lsb_release -a
    - run: uname -a
    - uses: actions/checkout@v4
    - name: Setup node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
    - run: sudo apt-get install xvfb libpulse0

    - run: npm install -g npm@10.2.5

    - name: Cache Desktop node_modules
      id: cache-desktop-modules
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-${{ hashFiles('package.json', 'package-lock.json', 'patches/**') }}

    - name: Install Desktop node_modules
      if: steps.cache-desktop-modules.outputs.cache-hit != 'true'
      run: npm ci
      env:
        NPM_CONFIG_LOGLEVEL: verbose

    - run: npm run generate
    - run: npm run prepare-beta-build

    - name: Create bundle
      run: npm run build:esbuild:prod

    - name: Build with packaging .deb file
      run: npm run build:release -- --publish=never
      env:
        DISABLE_INSPECT_FUSE: on

    # - run: xvfb-run --auto-servernum npm run test-node
    # - run: xvfb-run --auto-servernum npm run test-electron
    #   timeout-minutes: 5
    #   env:
    #     ARTIFACTS_DIR: artifacts/linux
    #     LANG: en_US
    #     LANGUAGE: en_US
    # - run: xvfb-run --auto-servernum npm run test-release
    #   env:
    #     NODE_ENV: production

    - name: Upload artifacts
      id: upload-artifacts
      uses: actions/upload-artifact@v4
      with:
        name: deb-package
        path: release//signal-desktop*.deb

  windows:
    needs: lint
    runs-on: windows-2019
    timeout-minutes: 30

    env:
      BUILD_LOCATION: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Tools\\MSVC\\14.29.30133\\lib\\x86\\store\\references\\"
      SDK_LOCATION: "C:\\Program Files (x86)\\Windows Kits\\10\\UnionMetadata\\10.0.17134.0"

    steps:
    - run: systeminfo
    - run: git config --global core.autocrlf false
    - run: git config --global core.eol lf
    - uses: actions/checkout@v4
    - name: Setup node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
    - run: npm install -g npm@10.2.5 node-gyp@10.0.1

    # Set things up so @nodert-win10-rs4 dependencies build properly
    - run: dir "$env:BUILD_LOCATION"
    - run: dir "$env:SDK_LOCATION"
    - run: "copy \"$env:BUILD_LOCATION\\platform.winmd\" \"$env:SDK_LOCATION\""
    - run: dir "$env:SDK_LOCATION"

    - name: Cache Desktop node_modules
      id: cache-desktop-modules
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-${{ hashFiles('package.json', 'package-lock.json', 'patches/**') }}

    - name: Install Desktop node_modules
      if: steps.cache-desktop-modules.outputs.cache-hit != 'true'
      run: npm ci
      env:
        CHILD_CONCURRENCY: 1
        NPM_CONFIG_LOGLEVEL: verbose

    - run: npm run generate
    - run: npm run test-node
    - run: copy package.json temp.json
    - run: del package.json
    - run: type temp.json | findstr /v certificateSubjectName | findstr /v certificateSha1 > package.json
    - run: npm run prepare-beta-build

    - name: Create bundle
      run: npm run build:esbuild:prod

    - name: Build with NSIS
      run: npm run build:release
      env:
        DISABLE_INSPECT_FUSE: on

    - run: npm run test-electron
      env:
        ARTIFACTS_DIR: artifacts/windows
      timeout-minutes: 5
    - run: npm run test-release
      env:
        SIGNAL_ENV: production

    - name: Upload artifacts
      id: upload-artifacts
      uses: actions/upload-artifact@v4
      with:
        name: installer-exe
        path: release//signal-desktop*.exe
